common/models/Wiki.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "wiki".
 *
 * @property int $id
 * @property int $id_project
 * @property string $title
 * @property string $content
 * @property int $status
 * @property int $created_at
 * @property int $updated_at
 */
class Wiki extends \yii\db\ActiveRecord {

    /**
     * @inheritdoc
     */
    public static function tableName() {
        return 'wiki';
    }

    /**
     * @inheritdoc
     */
    public function rules() {
        return [
            [['id_project', 'title', 'status', 'created_at', 'updated_at'], 'required'],
            [['id_project', 'status', 'created_at', 'updated_at'], 'integer'],
            [['content'], 'string'],
            [['title'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'id' => Yii::t('app', 'ID'),
            'id_project' => Yii::t('app', 'Project'),
            'title' => Yii::t('app', 'Title'),
            'content' => Yii::t('app', 'Content'),
            'status' => Yii::t('app', 'Status'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Last Updated'),
        ];
    }

    public function afterSave($insert, $changedAttributes) {
        parent::afterSave($insert, $changedAttributes);
        $author = new WikiUser();
        $author->id_wiki = $this->id;
        $author->id_user = Yii::$app->user->identity->id;
        $author->created_at = time();
        $author->updated_at = time();
        $author->save();
    }

    public function getHistories() {
        return $this->hasMany(WikiUser::className(), ['id_wiki' => 'id']);
    }

    public function getProject() {
        return $this->hasOne(Project::className(), ['id' => 'id_project']);
    }

}

frontend/controllers/WikiController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\Wiki;
use frontend\models\WikiSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * WikiController implements the CRUD actions for Wiki model.
 */
class WikiController extends Controller {

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Wiki models.
     * @return mixed
     */
    public function actionIndex($id_project = null) {
        $searchModel = new WikiSearch();
        if (!is_null($id_project)) {
            $searchModel->id_project = $id_project;
        } else {
            $searchModel->status = 1;
        }
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render(is_null($id_project) ? 'index_null' : 'index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
                    'id_project' => $id_project,
        ]);
    }

    /**
     * Displays a single Wiki model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id) {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Wiki model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($id_project) {
        $model = new Wiki();
        $model->id_project = $id_project;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
                    'model' => $model,
        ]);
    }

    /**
     * Updates an existing Wiki model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
                    'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Wiki model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id) {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Wiki model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Wiki the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Wiki::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }

    public function actionApprove($id) {
        $model = $this->findModel($id);
        $model->status = 1;
        $model->updated_at = time();
        if ($model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }
    }

    public function actionTimeline($id) {
        return $this->render('timeline', [
                    'model' => $this->findModel($id),
        ]);
    }

}

frontend/views/wiki/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use dosamigos\tinymce\TinyMce;

/* @var $this yii\web\View */
/* @var $model common\models\Wiki */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="wiki-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'id_project', ['options' => ['class' => 'hide']])->hiddenInput() ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?=
    $form->field($model, 'content')->widget(TinyMce::className(), [
        'options' => ['rows' => 6],
        'clientOptions' => [
            'plugins' => [
                'advlist autolink lists link image charmap print preview anchor textcolor',
                'searchreplace visualblocks code fullscreen',
                'insertdatetime media table contextmenu paste code help wordcount'
            ],
            'toolbar' => 'undo redo |  formatselect | bold italic backcolor  | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat | help',
        ]
    ]);
    ?>
    <?php if ($model->isNewRecord): ?>
        <?= $form->field($model, 'created_at', ['options' => ['class' => 'hide']])->hiddenInput(['value' => time()]) ?>
    <?php endif; ?>

    <?= $form->field($model, 'updated_at', ['options' => ['class' => 'hide']])->hiddenInput(['value' => time()]) ?>

    <?= $form->field($model, 'status', ['options' => ['class' => 'hide']])->hiddenInput(['value' => 0]) ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/wiki/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\WikiSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="wiki-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'id_project') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'content') ?>

    <?= $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/wiki/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Wiki */

$this->title = Yii::t('app', 'Create Wiki');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Projects'), 'url' => ['/project/index']];
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Wiki'), 'url' => ['index', 'id_project' => $model->id_project]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="wiki-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?=
    $this->render('_form', [
        'model' => $model,
    ])
    ?>

</div>

frontend/views/wiki/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use common\models\Project;
use kartik\tabs\TabsX;

/* @var $this yii\web\View */
/* @var $searchModel frontend\models\WikiSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Wiki');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Projects'), 'url' => ['/project/index']];
$this->params['breadcrumbs'][] = $this->title;
$project = Project::find()->where(['id' => $id_project])->one();
?>
<div class="wiki-index">

    <h1><?= Html::encode($project->name) ?></h1>

    <?=
    TabsX::widget([
        'position' => TabsX::POS_ABOVE,
        'align' => TabsX::ALIGN_RIGHT,
        'sideways' => true,
        'items' => [
            [
                'label' => Yii::t('app', 'Task'),
                'url' => ['task/project/' . $id_project],
            ],
            [
                'label' => Yii::t('app', 'Meeting'),
                'url' => ['meeting/project/' . $id_project],
            ],
            [
                'label' => Yii::t('app', 'Document'),
                'url' => ['document/project/' . $id_project],
            ],
            [
                'label' => Yii::t('app', 'Wiki'),
                'url' => ['wiki/project/' . $id_project],
                'active' => true
            ],
        ],
    ]);
    ?>
    <?php if (count($dataProvider->models) <= 0): ?>
        <p>
            <?= Html::a(Yii::t('app', 'Add'), ['create', 'id_project' => $id_project], ['class' => 'btn btn-success']) ?>
        </p>
    <?php endif; ?>
    <?=
    GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            [
                'attribute' => 'title',
                'filterInputOptions' => [
                    'class' => 'form-control',
                    'placeholder' => Yii::t('app', 'Search here')
                ]
            ], 'created_at:datetime',
            'updated_at:datetime',
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{view}'
            ],
        ],
    ]);
    ?>
</div>

frontend/views/wiki/index_null.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel frontend\models\WikiSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Wiki');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="wiki-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?=
    GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            [
                'attribute' => 'id_project',
                'format' => 'raw',
                'value' => function($model) {
                    return$model->project->name;
                }
            ],
            [
                'attribute' => 'title',
                'filterInputOptions' => [
                    'class' => 'form-control',
                    'placeholder' => Yii::t('app', 'Search here')
                ]
            ], 'updated_at:datetime',
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{view}',
                'buttons' => [
                    'view' => function ($url, $model, $key) {
                        return Html::a("<span class='glyphicon glyphicon-eye-open'></span>", ['timeline', 'id' => $model->id]);
                    }
                ]
            ],
        ],
    ]);
    ?>
</div>

frontend/views/wiki/timeline.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use vivekmarakana\widgets\Timeline;

/* @var $this yii\web\View */
/* @var $model common\models\Wiki */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Wiki'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="wiki-view">

    <h1><?= Html::encode($this->title) ?></h1>
    <div class="row">
        <div class="col-xs-8">
            <p class="text-muted"><?= Yii::t('app', 'Created') . ': ' . date('d-m-Y', $model->created_at) . ' | ' . Yii::t('app', 'Edited') . ': ' . count($model->histories) . 'x' ?></p>
            <hr/>
            <?= $model->content ?>
            <h3><?= Yii::t('app', 'Log') ?></h3>
            <table class="table table-responsive table-bordered">
                <thead>
                    <tr>
                        <th><?= Yii::t('app', 'Name') ?></th>
                        <th><?= Yii::t('app', 'Last Updated') ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($model->histories as $history): ?>
                        <tr>
                            <td><?= $history->user->profile->name ?></td>
                            <td><?= date('d-M-Y H:i', $history->created_at) ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <div class="col-xs-4">
            <?php
            $items = [];
            foreach ($model->project->tasks as $post) {
                $data = [];
                $data['title'] = $post->name;
                $data['date'] = date('d-m-Y', $post->start_plan_at);
                $data['time'] = date('H:i', $post->start_plan_at);
//                $data['notes'] = $post->description;
                $items[] = $data;
            }
            echo Timeline::widget(['items' => $items]);
            ?>
        </div>
    </div> 
</div>

frontend/views/wiki/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Wiki */

$this->title = Yii::t('app', 'Update Wiki: {nameAttribute}', [
            'nameAttribute' => $model->title,
        ]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Projects'), 'url' => ['/project/index']];
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Wiki'), 'url' => ['index', 'id_project' => $model->id_project]];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="wiki-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?=
    $this->render('_form', [
        'model' => $model,
    ])
    ?>

</div>

frontend/views/wiki/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Wiki */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Projects'), 'url' => ['/project/index']];
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Wiki'), 'url' => ['index', 'id_project' => $model->id_project]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="wiki-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Edit'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?php if ($model->project->id_user == Yii::$app->user->identity->id && $model->status != 1): ?>
            <?= Html::a(Yii::t('app', 'Approve'), ['approve', 'id' => $model->id], ['class' => 'btn btn-success']) ?>
            <?=
            Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                    'method' => 'post',
                ],
            ])
            ?>
        <?php endif; ?>
    </p>
    <p class="text-muted"><?= Yii::t('app', 'Created') . ': ' . date('d-m-Y', $model->created_at) . ' | ' . Yii::t('app', 'Edited') . ': ' . count($model->histories) . 'x' ?></p>
    <hr/>
    <?= $model->content ?>    <h3><?= Yii::t('app', 'Log') ?></h3>
    <table class="table table-responsive table-bordered">
        <thead>
            <tr>
                <th><?= Yii::t('app', 'Name') ?></th>
                <th><?= Yii::t('app', 'Last Updated') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($model->histories as $history): ?>
                <tr>
                    <td><?= $history->user->profile->name ?></td>
                    <td><?= date('d-M-Y H:i', $history->created_at) ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

</div>